**Python - Twitter API**

##                                            FETCHING DATA from TWITTER

import tweepy

In [1]:
#where all your packages are installed
#import sys
#sys.path

In [2]:
from tweepy import Stream
from tweepy import OAuthHandler
from tweepy.streaming import StreamListener


In [3]:
#Consumer Key (API Key): 
ckey = "*****************"
#Consumer Secret (API Secret): 
csecret = "**********"
#Access Token: 
atoken = "************"
#Access Token Secret:
asecret = "***********"

# --------------------------------------------------------------------
#Saving tweets in a csv file - need not run this cell
# --------------------------------------------------------------------

class listener(StreamListener):

   class listener(StreamListener):

    def on_data(self, data):
        try: 
            tweet = data.split(',"text":"')[1].split('","source')[0]
            print(tweet.full_text)
            return(True)
        except(BaseException, e):
            print('failed on data, ', str(e))
            time.sleep(5)
                    
    def on_error(self, status):
        print(status)
                    

auth = OAuthHandler(ckey, csecret)
auth.set_access_token(atoken, asecret)

twitterStream = Stream(auth, listener())
twitterStream.filter(track=["#winterolympics"])

In [46]:
# --------------------------
# Topic specific tweets
# --------------------------
import pandas as pd
import tweepy

OAUTH_KEYS = {'consumer_key':ckey, 'consumer_secret':csecret,
 'access_token_key':atoken, 'access_token_secret':asecret}
auth = tweepy.OAuthHandler(OAUTH_KEYS['consumer_key'], OAUTH_KEYS['consumer_secret'])
api = tweepy.API(auth)

trump = tweepy.Cursor(api.search, q='@realDonaldTrump', tweet_mode='extended').items(500) ####IMP tweet_mode='extended'##########

newdf = pd.DataFrame()
times = []
tweeter = []
language = []
for tweet in trump:
    #print(tweet.created_at, tweet.full_text, tweet.lang)
    #print('\n')
    #times.append(tweet.created_at)
    tweeter.append(tweet.full_text) #full_text IMP#########################################3
    #language.append(tweet.lang)
    
#newdf['Time'] = times
newdf['Tweet'] = tweeter
#newdf['Lang']=language


newdf.to_csv('C:/Users/nisha/Documents/DATA 903/Text Mining/Twitter/DonaldTrump.csv')

In [47]:
# ------------------------------------------------
# Importing tweets from a particular account
# ------------------------------------------------

OAUTH_KEYS = {'consumer_key':ckey, 'consumer_secret':csecret,
 'access_token_key':atoken, 'access_token_secret':asecret}
auth = tweepy.OAuthHandler(OAUTH_KEYS['consumer_key'], OAUTH_KEYS['consumer_secret'])
api = tweepy.API(auth)

trump = tweepy.Cursor(api.user_timeline,id = "@jimmykimmel", tweet_mode='extended', tweet_lang='en').items(500)

jimmy = pd.DataFrame()
times = []
tweeter = []
language = []
for tweet in trump:
    #print("likes = ", tweet.favorite_count, "num of retweets = ", tweet.retweet_count)
    #print('\n')
    #times.append(tweet.created_at)
    tweeter.append(tweet.full_text)
    #language.append(tweet.lang)

#jimmy['Time'] = times
jimmy['Tweet'] = tweeter
#jimmy['Lang'] = language
jimmy.to_csv('C:/Users/nisha/Documents/DATA 903/Text Mining/Twitter/jimmykimmel.csv')


In [48]:
# ------------------------------------------------
# Importing tweets from a particular account
# ------------------------------------------------

OAUTH_KEYS = {'consumer_key':ckey, 'consumer_secret':csecret,
 'access_token_key':atoken, 'access_token_secret':asecret}
auth = tweepy.OAuthHandler(OAUTH_KEYS['consumer_key'], OAUTH_KEYS['consumer_secret'])
api = tweepy.API(auth)

trump = tweepy.Cursor(api.user_timeline,id = "@MileyCyrus", tweet_mode='extended', tweet_lang='en').items(500)

miley = pd.DataFrame()
times = []
tweeter = []
language = []
for tweet in trump:
    #print("likes = ", tweet.favorite_count, "num of retweets = ", tweet.retweet_count)
    #print('\n')
    #times.append(tweet.created_at)
    tweeter.append(tweet.full_text)
    #language.append(tweet.lang)

#jimmy['Time'] = times
miley['Tweet'] = tweeter
#jimmy['Lang'] = language
miley.to_csv('C:/Users/nisha/Documents/DATA 903/Text Mining/Twitter/mileycyrus.csv')


In [49]:
import csv 

OAUTH_KEYS = {'consumer_key':ckey, 'consumer_secret':csecret,
 'access_token_key':atoken, 'access_token_secret':asecret}

auth = tweepy.OAuthHandler(OAUTH_KEYS['consumer_key'], OAUTH_KEYS['consumer_secret'])

api = tweepy.API(auth)

# Open/create a file to append data to
#csvFile = open('C:/Users/nisha/Documents/DATA 903/Text Mining/Twitter/mileycyrus.csv', 'a')

#Use csv writer
#csvWriter = csv.writer(csvFile)


#for tweet in tweepy.Cursor(api.search, q = ["@MileyCyrus"], tweet_mode='extended', lang = "en").items(50):
    # Write a row to the CSV file. 
    #csvWriter.writerow([tweet.full_text])


#csvFile.close()


In [50]:
# ------------------------------------------------
# Importing tweets from a particular account
# ------------------------------------------------

OAUTH_KEYS = {'consumer_key':ckey, 'consumer_secret':csecret,
 'access_token_key':atoken, 'access_token_secret':asecret}
auth = tweepy.OAuthHandler(OAUTH_KEYS['consumer_key'], OAUTH_KEYS['consumer_secret'])
api = tweepy.API(auth)

# Scrapping an ID
trump = tweepy.Cursor(api.user_timeline,id = "@winklevoss",tweet_mode='extended', lang='en').items(500)

wv = pd.DataFrame()
times = []
tweeter = []
language = []
for tweet in trump:
    print("likes = ", tweet.favorite_count, "num of retweets = ", tweet.retweet_count)
    print('\n')
    #times.append(tweet.created_at)
    tweeter.append(tweet.full_text)
    #language.append(tweet.lang)

#wv['Time'] = times
wv['Tweet'] = tweeter
#wv['Lang'] = language
wv.to_csv('C:/Users/nisha/Documents/DATA 903/Text Mining/Twitter/winklevoss.csv')

likes =  0 num of retweets =  41


likes =  26 num of retweets =  3


likes =  29 num of retweets =  3


likes =  0 num of retweets =  387


likes =  0 num of retweets =  45


likes =  0 num of retweets =  146


likes =  0 num of retweets =  17


likes =  0 num of retweets =  5


likes =  0 num of retweets =  116


likes =  0 num of retweets =  801


likes =  0 num of retweets =  106


likes =  0 num of retweets =  38


likes =  0 num of retweets =  821


likes =  0 num of retweets =  103


likes =  0 num of retweets =  126


likes =  0 num of retweets =  52


likes =  0 num of retweets =  46


likes =  0 num of retweets =  17


likes =  0 num of retweets =  9


likes =  0 num of retweets =  60


likes =  0 num of retweets =  12


likes =  115 num of retweets =  25


likes =  0 num of retweets =  9


likes =  0 num of retweets =  19


likes =  8 num of retweets =  1


likes =  6 num of retweets =  0


likes =  3 num of retweets =  0


likes =  3 num of retweets =  0


likes =  4 num of

In [51]:
# ------------------------------------------------
# Importing tweets from a particular account
# ------------------------------------------------

OAUTH_KEYS = {'consumer_key':ckey, 'consumer_secret':csecret,
 'access_token_key':atoken, 'access_token_secret':asecret}
auth = tweepy.OAuthHandler(OAUTH_KEYS['consumer_key'], OAUTH_KEYS['consumer_secret'])
api = tweepy.API(auth)

# Scrapping an ID
trump = tweepy.Cursor(api.user_timeline,id = "@KimKardashian",tweet_mode='extended', lang='en').items(500)

kim = pd.DataFrame()
times = []
tweeter = []
language = []
for tweet in trump:
    print("likes = ", tweet.favorite_count, "num of retweets = ", tweet.retweet_count)
    print('\n')
    #times.append(tweet.created_at)
    tweeter.append(tweet.full_text)
    #language.append(tweet.lang)

#wv['Time'] = times
kim['Tweet'] = tweeter
#wv['Lang'] = language
kim.to_csv('C:/Users/nisha/Documents/DATA 903/Text Mining/Twitter/kim.csv')

likes =  1300 num of retweets =  114


likes =  0 num of retweets =  70


likes =  0 num of retweets =  95


likes =  0 num of retweets =  620


likes =  0 num of retweets =  43


likes =  0 num of retweets =  41


likes =  4880 num of retweets =  244


likes =  0 num of retweets =  42


likes =  3130 num of retweets =  149


likes =  2723 num of retweets =  161


likes =  2334 num of retweets =  168


likes =  1820 num of retweets =  109


likes =  0 num of retweets =  146


likes =  21966 num of retweets =  2166


likes =  4331 num of retweets =  320


likes =  0 num of retweets =  65


likes =  4130 num of retweets =  168


likes =  11636 num of retweets =  572


likes =  0 num of retweets =  254


likes =  0 num of retweets =  60


likes =  3433 num of retweets =  184


likes =  0 num of retweets =  72


likes =  0 num of retweets =  57


likes =  3811 num of retweets =  118


likes =  3701 num of retweets =  191


likes =  0 num of retweets =  101


likes =  0 num of retweets =  4

In [52]:
kim.head()

Tweet
0  So excited to share an exclusive first look at...
1  RT @TeamKanyeDaily: TIMES SQUARE\n#YEEZYSEASON...
2  RT @TeamKanyeDaily: #YEEZYSEASON6 https://t.co...
3  RT @TeamKanyeDaily: YEEZY SEASON 6 | TIMES SQU...
4  RT @kkwbeauty: New individual Crème Sticks for...

In [53]:
wv.head()

Tweet
0  RT @IBKR: #Bitcoin's recent historical breakth...
1  Did you follow yours today? https://t.co/A6kx9...
2  Really enjoyed the vision and insight of my fe...
3  RT @tylerwinklevoss: Bitcoin is gaining curren...
4  RT @tylerwinklevoss: Meet the candidate paying...

In [54]:
miley.head()

Tweet
0  Chillin w an American legend .... &amp; I mean...
1  RT @ForParkland: Get ready because change is c...
2  RT @AMarch4OurLives: On March 24 we will take ...
3  Happy bday lil sis @milliebbrown https://t.co/...
4        Feeling my oats LOL https://t.co/uFK0Rl9T4L

In [55]:
jimmy.head()

Tweet
0  Tonight on #Kimmel @BatemanJason #GameNight, @...
1  .@RealDonaldTrump lends his full support to @M...
2  A NEW edition of the Winter #Youlympics brough...
3  I got CAUGHT ON CAMERA at the #NBAAllStar game...
4  At long last, @IamGuillermo's EXCLUSIVO with @...

In [56]:
newdf.head()

Tweet
0  RT @realDonaldTrump: I will always remember th...
1  Donald Trump &amp; Robert Kiyosaki, "Why We Wa...
2  RT @KurtSchlichter: So why are hard-core conse...
3  @realDonaldTrump A true leader doesn’t need no...
4  @realDonaldTrump How is this tweet feeling? Ki...

In [57]:
df = newdf.append(jimmy)
df = df.append(miley)
df = df.append(kim)
df = df.append(wv)

In [58]:
df

Tweet
0    RT @realDonaldTrump: I will always remember th...
1    Donald Trump &amp; Robert Kiyosaki, "Why We Wa...
2    RT @KurtSchlichter: So why are hard-core conse...
3    @realDonaldTrump A true leader doesn’t need no...
4    @realDonaldTrump How is this tweet feeling? Ki...
5           @realDonaldTrump #BEST DAMN PRESIDENT EVER
6    @realDonaldTrump Your stupidity is something I...
7    RT @maysoonzayid: #StudentsStandUp Even on thi...
8             @realDonaldTrump https://t.co/yqSykRiGC2
9    RT @LynnePatton: @NoahFinneburgh @realDonaldTr...
10   @realDonaldTrump when you have to remind yours...
11   @realDonaldTrump notes, really? Sociopaths don...
12   Mark my words if @realDonaldTrump keeps pushin...
13   RT @Coreybez1: @realDonaldTrump  https://t.co/...
14   @LiberatedCit @realDonaldTrump The world to cu...
15   RT @johncardillo: .@realDonaldTrump has exhibi...
16   RT @Jillibean557: @realDonaldTrump We support ...
17   RT @JARosenberg12: More crap #DonaldTrump forg...
18   @realDonaldTrump @LouDobbs But there were many...
19   RT @HolzMAS: @FoxNews @POTUS I love @realDonal...
20   @chibearfan74_jr @realDonaldTrump The son of f...
21   RT @koopster90: @THETXEMBASY @lerae4428 @BobPr...
22   RT @ErinMcPike: @barackobama has more than dou...
23   RT @piersmorgan: NO, Mr President @realDonaldT...
24   RT @realDonaldTrump: The GREAT Billy Graham is...
25   RT @SirMayankRathod: @realDonaldTrump Accordin...
26   @realDonaldTrump And I would find a place for ...
27   RT @BFM68133189: @jerome_corsi @realDonaldTrum...
28   @realDonaldTrump I disagree with your solution...
29        @DavidWohl @realDonaldTrump Well said David.
..                                                 ...
470  "I think there's a lot of merit behind it" -Ra...
471  Winklevoss Twins Say Bitcoin Market To Hit $40...
472  RT @emraguso: Judging from their socks, @winkl...
473  RT @RedditBTC: I'm at Ignition 2013. The Winkl...
474  Talking #bitcoin with @andrewrsorkin + @tylerw...
475  RT @winklevosscap: Bitcoin: Bubble or Boon? wi...
476  On air @cnbcsocial with @andrewrsorkin and @ty...
477  RT @winklevosscap: See @winklevoss and @tylerw...
478  RT @Bill_Gross: This is kind of amazing, the c...
479  Price of #bitcoin trading at $275 USD on #bits...
480  Sad 2 c Blockbuster go, remember when searchin...
481  Today is the 5 year anniversary of Satoshi Nak...
482  Working to make #bitcoin mainstream day by day...
483  RT @joesonheim: The Winklevoss twins kind of l...
484  RT @businessinsider: Nest, Tesla, Uber, Union ...
485  RT @ScottBoehme: "Some countries may eventuall...
486  RT @winklevosscap: Talking Bitcoin with @Chuck...
487  Talking with @ChuckSalter and @tylerwinklevoss...
488  RT @ChuckSalter: Brother, can you spare a byte...
489  RT @avyfain: .@winklevoss, after #tcdisrupt we...
490  RT @winklevosscap: Excited about our latest in...
491  RT @SteveMartinToGo: Used a bitcoin to buy an ...
492  #bitcoinbelievers cc @tylerwinklevoss @winklev...
493  Reports of #silkroad influence, impact + relev...
494  RT @tylerwinklevoss: #silkroad never accounted...
495  RT @tylerwinklevoss: #silkroad indicates the s...
496  RT @winklevosscap: How the Winklevoss twins di...
497  This Presentation Won An Investor $50,000 At A...
498  RT @KoppTheFool: No fan of #Bitcoin here, but ...
499  Perhaps the only thing better than a #bitcoin ...

[2500 rows x 1 columns]

In [59]:
listdf =[]
for i in df['Tweet']:
    listdf.append(i)
    

In [60]:
listdf[0]

'RT @realDonaldTrump: I will always remember the time I spent today with courageous students, teachers and families. So much love in the mid…'

In [61]:
#y = df['Person']

In [62]:
#defining the DTM

from nltk.tokenize import RegexpTokenizer
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk import wordpunct_tokenize
en_stop = stopwords.words('english')
# Alternative tokenizer
tokenizer = RegexpTokenizer(r'\w+')

en_stop = stopwords.words('english')

# Create p_stemmer of class PorterStemmer
p_stemmer = PorterStemmer()

# Adding period to stop list
en_stop.extend([".","-","(", ")","/", ",", "’", "”","“","!","}"])

print(en_stop)


stemmer = PorterStemmer()
def stem_tokens(tokens, stemmer):
    stemmed = []
    for item in tokens:
        stemmed.append(stemmer.stem(item))
    return stemmed

def tokenize(text):
    tokens = nltk.word_tokenize(text)
    stems = stem_tokens(tokens, stemmer)
    return stems

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', 'her', 'hers', 'herself', 'it', 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', 'too', 'very', 's', 't', 'can', 'will', 'just', 'don', 'should', 'no

In [65]:
import os
from sklearn.feature_extraction.text import CountVectorizer
import nltk
from nltk import word_tokenize          
from nltk.stem.porter import PorterStemmer
from nltk.tokenize import RegexpTokenizer
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk import wordpunct_tokenize

vect = CountVectorizer(tokenizer = tokenize, stop_words = en_stop, ngram_range= (1,3), lowercase= True,max_features = 150)

dtm = vect.fit_transform(listdf)

print(dtm.shape)

df_dtm = pd.DataFrame(dtm.toarray(), columns = vect.get_feature_names())
print(df_dtm.head())

(2500, 150)
   #  # bitcoin  # teammiley  $  %  &  & amp  & amp ;  ''  're ...  watch  \
0  0          0            0  0  0  0      0        0   0    0 ...      0   
1  0          0            0  0  0  1      1        1   1    0 ...      0   
2  0          0            0  0  0  0      0        0   0    0 ...      0   
3  2          0            0  0  0  0      0        0   0    0 ...      0   
4  0          0            0  0  0  0      0        0   0    0 ...      0   

   whi  winklevoss  winklevoss @  winklevoss @ tylerwinklevoss  winklevosscap  \
0    0           0             0                             0              0   
1    1           0             0                             0              0   
2    1           0             0                             0              0   
3    0           0             0                             0              0   
4    0           0             0                             0              0   

   winklevosscap :  would  year  …  
0

In [66]:
pd.set_option('display.max_columns', 500)
df_dtm.head()

#  # bitcoin  # teammiley  $  %  &  & amp  & amp ;  ''  're  's  ...  \
0  0          0            0  0  0  0      0        0   0    0   0    0   
1  0          0            0  0  0  1      1        1   1    0   0    0   
2  0          0            0  0  0  0      0        0   0    0   0    0   
3  2          0            0  0  0  0      0        0   0    0   0    1   
4  0          0            0  0  0  0      0        0   0    0   0    0   

   ... http  ... http :  :  : #  : @  : @ realdonaldtrump  : http  : http :  \
0         0           0  1    0    0                    0       0         0   
1         0           0  1    0    0                    0       0         0   
2         0           0  1    0    0                    0       0         0   
3         0           0  1    0    0                    0       0         0   
4         0           0  0    0    0                    0       0         0   

   ;  ; @  ?  @  @ brookesimpson  @ geminidotcom  @ geminidotcom :  \
0  0    0  0  1                0               0                 0   
1  1    0  0  2                0               0                 0   
2  0    0  0  2                0               0                 0   
3  0    0  0  2                0               0                 0   
4  0    0  1  1                0               0                 0   

   @ kimkardashian  @ kkwfragranc  @ mileycyru  @ nbcthevoic  @ nbcthevoic :  \
0                0              0            0             0               0   
1                0              0            0             0               0   
2                0              0            0             0               0   
3                0              0            0             0               0   
4                0              0            0             0               0   

   @ realdonaldtrump  @ realdonaldtrump :  @ realdonaldtrump @  \
0                  1                    1                    0   
1                  1                    0                    1   
2                  1                    0                    0   
3                  1                    0                    0   
4                  1                    0                    0   

   @ tylerwinklevoss  @ tylerwinklevoss :  @ tylerwinklevoss @  @ winklevoss  \
0                  0                    0                    0             0   
1                  0                    0                    0             0   
2                  0                    0                    0             0   
3                  0                    0                    0             0   
4                  0                    0                    0             0   

   @ winklevoss @  @ winklevosscap  @ winklevosscap :  ``  alway  amp  amp ;  \
0               0                0                  0   0      1    0      0   
1               0                0                  0   1      0    1      1   
2               0                0                  0   0      0    0      0   
3               0                0                  0   0      0    0      0   
4               0                0                  0   0      0    0      0   

   amp ; @  auction  beauti  becaus  best  bitcoin  brookesimpson  btc  come  \
0        0        0       0       0     0        0              0    0     0   
1        0        0       0       0     0        0              0    0     0   
2        0        0       0       1     0        0              0    0     0   
3        0        0       0       0     0        0              0    0     0   
4        0        0       0       0     0        0              0    0     0   

   day  doe  ever  famili  first  gemini  geminidotcom  geminidotcom :  get  \
0    0    0     0       1      0       0             0               0    0   
1    0    0     0       0      0       0             0               0    0   
2    0    0     0       0      0       0             0               0    0   
3    0    0     0  

In [67]:
#creating an extra column
df_dtm['Person'] = 0

In [68]:
#assigning the y columns
df_dtm['Person'][0:500] = 0
df_dtm['Person'][500:1000] = 1
df_dtm['Person'][1000:1500] = 2
df_dtm['Person'][1500:2000] = 3 
df_dtm['Person'][2000:2500] = 4

In [69]:
#df_dtm.isnull().sum()
df_dtm = df_dtm.fillna(0)

In [70]:
#retrieving required column indices for X and Y
y_index=df_dtm.columns.get_loc("Person")

In [71]:
y_index

150

In [73]:
import numpy as np
dtm=df_dtm.as_matrix()

X=np.delete(dtm,y_index,axis=1)

Y=dtm[:,y_index]

In [74]:
y = pd.factorize(Y)[0]  #Encode input values as an enumerated type or categorical variable
len(y)

# Frequency distribution
from scipy import stats
stats.itemfreq(y) # displays how many times 0 is repeated and 1 is repeated


array([[  0, 500],
       [  1, 500],
       [  2, 500],
       [  3, 500],
       [  4, 500]], dtype=int64)

In [88]:
from sklearn.cross_validation import train_test_split
import numpy

x_train ,x_test,y_train,y_test = train_test_split(X,y,test_size=0.4, random_state=42) 

In [89]:
# Basic code for setting up a model
from keras.models import Sequential
from keras.layers import Dense
from keras import optimizers
import numpy as np

In [90]:
#One-hot encoding: Needed if the categorical variable is stored as numeric
from keras.utils import to_categorical

#y_cat = to_categorical(y_train)
y_cat = pd.get_dummies(y_train)

# Save the number of columns in predictors: n_cols
n_cols = x_train.shape[1]
print(n_cols)
# Set up the model: model
model = Sequential()

# Add the first layer
model.add(Dense(80, activation='relu', input_shape=(n_cols,)))
# Add the second layer
model.add(Dense(52, activation='relu'))
# Add the output layer

model.add(Dense(5, activation = 'softmax'))

#sgd = optimizers.SGD(lr=0.1)
#print(sgd)
model.compile(optimizer='adam',loss='categorical_crossentropy')

# Confirming that the model compiled correctly 
#print("Loss function: " + model.loss)

# Fitting the model
#model.fit(X, y)

#adding this
model.fit(x_train,y_cat,epochs = 10)


# Compile the model


# Fit the model
#model.fit(Xepa, yepa_cat)


150
Epoch 1/10
1500/1500 [==============================] - 1s 572us/step - loss: 1.4042
Epoch 2/10
1500/1500 [==============================] - 0s 58us/step - loss: 0.9250
Epoch 3/10
1500/1500 [==============================] - 0s 63us/step - loss: 0.6978
Epoch 4/10
1500/1500 [==============================] - 0s 68us/step - loss: 0.6199
Epoch 5/10
1500/1500 [==============================] - 0s 58us/step - loss: 0.5696

In [91]:
# Calculate predictions: predictions
predictions = model.predict(x_test)
print(predictions)

# # Calculate predicted probability of positive: predicted_prob_true
predicted_prob_true = predictions[:,1]

# # print predicted_prob_true
print(predicted_prob_true)


[[3.5558810e-06 1.0673210e-03 9.9279600e-01 5.6702890e-03 4.6291799e-04]
 [9.3324665e-08 2.7946651e-05 9.9995625e-01 1.4622032e-05 1.0443722e-06]
 [9.0917497e-04 5.4813609e-02 3.1174955e-01 6.1620295e-01 1.6324772e-02]
 ...
 [9.5942360e-01 3.1999912e-02 2.9127751e-03 4.0230770e-03 1.6406017e-03]
 [7.6647702e-05 3.9688062e-02 2.8078341e-01 6.5937859e-01 2.0073252e-02]
 [1.6095161e-07 3.3886815e-06 6.7942722e-07 1.2529767e-06 9.9999452e-01]]
[1.06732105e-03 2.79466512e-05 5.48136085e-02 2.09529642e-02
 1.07679814e-02 7.17890123e-03 5.87627143e-02 9.76323113e-02
 8.94568209e-03 1.27498610e-02 1.39699103e-02 1.48942461e-03
 8.56300294e-01 6.47908655e-06 4.73595351e-01 6.01649761e-01
 6.92389190e-01 4.04553525e-02 5.07537961e-01 2.13083308e-02
 8.14179584e-05 4.11254168e-01 3.68352653e-03 2.47244060e-07
 5.39797358e-04 5.73418319e-01 4.03651228e-07 3.09735298e-01
 1.23720776e-04 2.71005452e-01 2.62403185e-03 3.86521280e-01
 5.03553601e-04 2.83676600e-05 5.98786235e-01 7.93953314e-02
 5.6034

In [1]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

predictions = model.predict_classes(x_test)
print('\n')
print(pd.Series(predictions).value_counts(), '\n')
print(pd.Series(y_test).value_counts(), '\n')

print('Accuracy on test data:', accuracy_score(y_test, predictions), '\n')
print('Confusion matrix: ', '\n', confusion_matrix(y_test, predictions), sep = '')

NameError: name 'model' is not defined